name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy-ros-base

    steps:
      - uses: actions/checkout@v4
      - name: All test
        run: |
          chmod +x test/test.bash
          bash -xv test/test.bash /root
