name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy-ros-base

    steps:
      - uses: actions/checkout@v4
      - name: Prepare workspace 
        run: |
          mkdir -p /root/ros2_ws2025/src/mypkg
          rsync -av --delete ./ /root/ros2_ws2025/src/mypkg/
      - name: All test
        run: |
          chmod +x /root/ros2_ws2025/src/mypkg/test/test.bash
          bash -xv /root/ros2_ws2025/src/mypkg/test/test.bash /root
